language: csharp
solution: dotnet-chef-api.sln
install:
  - nuget restore
script:
  - xbuild dotnet-chef-api.sln
  - mono ./packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./src/unittests/bin/Release/EBSCO.ChefServertests.dll
  - nuget set ApiKey $NugetApiKey
  - nuget pack ./src/dotnet-chef-api/EBSCO.ChefServerApi.csproj
  - nuget push ./src/dotnet-chef-api/Ebsco.ChefServer.Api.nupkg