language: csharp
solution: dotnet-chef-api.sln
install:
  - nuget restore
script:
  - xbuild dotnet-chef-api.sln
  - mono ./packages.NUnit.ConsoleRunner.3.4.1.tools/nunit3-console.exe ./unittests/bin/Release/AuthenticatedChefRequest.Tests.dll