language: csharp
solution: dotnet-chef-api.sln
before_install:
  - nuget update -self
script:
  - xbuild dotnet-chef-api.sln
  - mono ./packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./src/unittests/bin/Release/EBSCO.ChefServer.Tests.dll
  - nuget set ApiKey $NugetApiKey
  - nuget pack ./src/dotnet-chef-api/EBSCO.ChefServerApi.csproj -IncludeReferencedProjects
  - nuget push ./src/dotnet-chef-api/Ebsco.ChefServer.Api.nupkg