language: csharp
solution: dotnet-chef-api.sln
install:
  - nuget restore dotnet-chef-api.sln
script:
  - xbuild /p:Configuration=Debug dotnet-chef-api.sln
  - mono ./testrunner/NUnit.Runners.*/tools/nunit-console.exe ./unittests/bin/Release/AuthenticatedChefRequest.Tests.dll