language: csharp
solution: dotnet-chef-api.sln
install:
  - nuget restore
script:
  - xbuild dotnet-chef-api.sln
  - mono ./testrunner/NUnit.Runners.*/tools/nunit-console.exe ./unittests/bin/Release/AuthenticatedChefRequest.Tests.dll