sudo: required
dist: trusty
language: csharp
mono: latest
script:
  #dotnet build
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
  - mono .nuget/nuget.exe setApiKey $NugetApiKey -Verbosity quiet
  - mono .nuget/nuget.exe restore
  - xbuild dotnet-chef-api.sln /p:Configuration=Release
  - mono ./packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./src/unittests/bin/Release/EBSCO.ChefServer.Tests.dll
  - .nuget/nuget.exe pack -help
  - .nuget/nuget.exe pack -sym
  - .nuget/nuget.exe pack -sym ./src/dotnet-chef-api/EBSCO.ChefServerApi.csproj -IncludeReferencedProjects
  #- .nuget/nuget.exe pack -sym ./src/dotnet-chef-api/EBSCO.ChefServerApi.csproj -IncludeReferencedProjects #-Version %BuildMajor%.%BuildMinor%.%BuildRevision%.%BuildNumber% -Prop Configuration=Release
  - .nuget/nuget.exe pack ./src/dotnet-chef-api/EBSCO.ChefServerApi.csproj -IncludeReferencedProjects
deploy:
  provider: script
  script: 
    #- mono .nuget/nuget.exe push ./src/dotnet-chef-api/Ebsco.ChefServer.Api.nupkg
  on:
    branch: tests